version: "3.8"
services:
  php-apache-environment:
    image: osc4ris/quiz2
    container_name: php-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
